### ISSUE TITLE
Crash in OpenGaze Example while using Gazepoint GP3 HD

### ISSUE THREAD

**Issue by chalgand** [esdalmaijer/PyGaze#103]
Hi,

After installing : 
- gazepoint software, 
- this pygaze project on anaconda distribution (python 2.7)
- psychopy, pygame

When i run example_pygaze.py, python said me : 

`runfile('C:/Users/halgang/Documents/PyOpenGaze/example/example_pygaze.py', wdir='C:/Users/halgang/Documents/PyOpenGaze/example')
Traceback (most recent call last):

  File "<ipython-input-1-f6bbb9125d48>", line 1, in <module>
    runfile('C:/Users/halgang/Documents/PyOpenGaze/example/example_pygaze.py', wdir='C:/Users/halgang/Documents/PyOpenGaze/example')

  File "C:\Users\halgang\AppData\Local\conda\conda\envs\py27\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\halgang\AppData\Local\conda\conda\envs\py27\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/halgang/Documents/PyOpenGaze/example/example_pygaze.py", line 13, in <module>
    tracker = EyeTracker(disp)

  File "C:\Users\halgang\AppData\Local\conda\conda\envs\py27\lib\site-packages\python_pygaze-0.6.0a21-py2.7.egg\pygaze\eyetracker.py", line 122, in __init__
    self.__class__.__init__(self, display, **args)

  File "C:\Users\halgang\AppData\Local\conda\conda\envs\py27\lib\site-packages\python_pygaze-0.6.0a21-py2.7.egg\pygaze\_eyetracker\libopengaze.py", line 143, in __init__
    logfile=self.outputfile, debug=False)

  File "C:\Users\halgang\AppData\Local\conda\conda\envs\py27\lib\site-packages\python_pygaze-0.6.0a21-py2.7.egg\pygaze\_eyetracker\opengaze.py", line 75, in __init__
    self._sock.connect((self.host, self.port))

  File "C:\Users\halgang\AppData\Local\conda\conda\envs\py27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)

error: [Errno 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

C:\Users\halgang\AppData\Local\conda\conda\envs\py27\lib\site-packages\traitlets\config\configurable.py:84: UserWarning: Config option `use_jedi` not recognized by `IPCompleter`.
  self.config = config
C:\Users\halgang\AppData\Local\conda\conda\envs\py27\lib\site-packages\dateutil\parser.py:605: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif res.tzname and res.tzname in time.tzname:`

Please, have you got an idea to help me ?

**Comment by chalgand** [comment]
Sorry, Gazepoint Control wasn't running...
