### ISSUE TITLE
Exception: The setting "TRACKERSERIALNUMBER" does not exist

### ISSUE THREAD

**Issue by Xinzhi-Wang** [esdalmaijer/PyGaze#146]
hello,

when I run this program with tobii Eye Tracker 4C, it will have something wrong. The traceback is as follow. The main problem is "The setting "TRACKERSERIALNUMBER" does not exist".

I would appreciate it if you could give me a solution. Thanks for your time.

Traceback (most recent call last):

  File "<ipython-input-9-24064fc48b04>", line 1, in <module>
    runfile('D:/anaconda_python_exercise/dataset/PyGaze/examples/slideshow/experiment.py', wdir='D:/anaconda_python_exercise/dataset/PyGaze/examples/slideshow')

  File "D:\Anaconda3\envs\py3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\envs\py3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/anaconda_python_exercise/dataset/PyGaze/examples/slideshow/experiment.py", line 30, in <module>
    tracker = EyeTracker(disp)

  File "D:\Anaconda3\envs\py3\lib\site-packages\pygaze\eyetracker.py", line 95, in __init__
    self.__class__.__init__(self, display, **args)

  File "D:\Anaconda3\envs\py3\lib\site-packages\pygaze\_eyetracker\libtobii.py", line 49, in __init__
    if hasattr(settings, 'TRACKERSERIALNUMBER'):

  File "D:\Anaconda3\envs\py3\lib\site-packages\pygaze\settings.py", line 51, in __getattr__
    raise Exception(u'The setting "%s" does not exist' % setting)

Exception: The setting "TRACKERSERIALNUMBER" does not exist

**Comment by esdalmaijer** [comment]
Add the variable `TRACKERSERIALNUMBER` to your constants.py file, adding in your tracker's serial number.
