### ISSUE TITLE
Can't run the annoying_message.py example

### ISSUE THREAD

**Issue by Pithikos** [esdalmaijer/PyGaze#29]
Trying to run the annoying_message.py example with Python2.7 gives me this error:

```
manos@manos-530U3C:~/PyGaze/examples/annoying_message$ python annoying_message.py 
Traceback (most recent call last):
  File "annoying_message.py", line 18, in <module>
    disp = Display()
  File "/usr/local/lib/python2.7/dist-packages/pygaze/display.py", line 43, in __init__
    from pygaze._display.psychopydisplay import PsychoPyDisplay  as Display
  File "/usr/local/lib/python2.7/dist-packages/pygaze/_display/psychopydisplay.py", line 30, in <module>
    from pygaze.libtime import clock
  File "/usr/local/lib/python2.7/dist-packages/pygaze/libtime.py", line 29, in <module>
    from pygaze._time.psychopytime import PsychoPyTime as Time
  File "/usr/local/lib/python2.7/dist-packages/pygaze/_time/psychopytime.py", line 22, in <module>
    import psychopy.core
ImportError: No module named psychopy.core
```

Trying to run it with Python3 gives me this error:

```
manos@manos-530U3C:~/PyGaze/examples/annoying_message$ python3 annoying_message.py 
Traceback (most recent call last):
  File "annoying_message.py", line 14, in <module>
    from pygaze.libscreen import Display, Screen
  File "/usr/local/lib/python3.3/dist-packages/pygaze/libscreen.py", line 22, in <module>
    from screen import Screen
ImportError: No module named 'screen'
```

**Comment by Taboen** [comment]
esdalmaijer, would you still not recommend using PyGaze with Python 3? You made this statement 3 years ago, so I'm wondering if it's still relevant. We are about to start a project using pygaze. (We want to be able to use two different eye trackers and mouse input to see what parts of images are looked at.)
