### ISSUE TITLE
Crash during testing with pygaze_trackertest

### ISSUE THREAD

**Issue by cyrus** [esdalmaijer/PyGaze#52]
I am trying to test pygaze on my system, and it seems to fail on the following part of the trackertest:

`$ python PyGaze_trackertest.py 
starting recording ...
returned 0
Start realtime mode ...
Wait for block start ...
done ...
stopping recording ...
done ...
status message: now testing sample function
starting recording ...
returned 0
Start realtime mode ...
Wait for block start ...
done ...
stopping recording ...
done ...
libeyelink.libeyelink.fix_triggered_drift_correction(): success
status message: now testing wait_for_event functions
Traceback (most recent call last):
  File "PyGaze_trackertest.py", line 159, in <module>
    eventfuncs[i]()
  File "/usr/local/lib/python2.7/dist-packages/pygaze/_eyetracker/libeyelink.py", line 843, in wait_for_fixation_start
    spos = self.sample()
  File "/usr/local/lib/python2.7/dist-packages/pygaze/_eyetracker/libeyelink.py", line 621, in sample
    "Error in libeyelink.libeyelink.sample(): Recording was not "
Exception: Error in libeyelink.libeyelink.sample(): Recording was not started before collecting eyelink data!
`
I am using pygaze version 0.6.0a6, synced with git today.
python 2.7
Ubunutu 14.04
most recent pylink version.

I also tried the other example programs, and they all seem to crash on the "wait_for_xxxx" function calls. Any ideas why this might be the case? Any ideas on how to dig deeper to debug?

Thanks so much,

Cyrus

**Comment by cyrus** [comment]
When I comment out the following tests, the rest of the tests pass
'''
	tracker.wait_for_fixation_start,
	tracker.wait_for_fixation_end,
	tracker.wait_for_saccade_start,
	tracker.wait_for_saccade_end,
	tracker.wait_for_blink_start,
	tracker.wait_for_blink_end,
'''

Also, there is a problem with the function: 
```
tracker.fix_triggered_drift_correction()
```
I have to press the ESCAPE key to break out of that one....

Any idea what is wrong,  @esdalmaijer or @smathot or others?

(I forgot to mention: I am testing this with @smathot 's fork of PyGaze.)

-Cyrus
