### ISSUE TITLE
Dummy tracker drawing error - "global name 'FGC' is not defined"

### ISSUE THREAD

**Issue by kasmith** [esdalmaijer/PyGaze#91]
I was trying PyGaze out on my laptop and couldn't get the simple demo to work because of the following error:

Traceback (most recent call last):
  File "simple_tracker_experiment.py", line 69, in <module>
    checked = tracker.drift_correction()
  File "/usr/local/lib/python2.7/site-packages/pygaze/_eyetracker/libdummytracker.py", line 103, in drift_correction
    self.draw_drift_correction_target(pos[0], pos[1])
  File "/usr/local/lib/python2.7/site-packages/pygaze/_eyetracker/libdummytracker.py", line 401, in draw_drift_correction_target
    self.screen.draw_fixation(fixtype='dot', colour=FGC, pos=(x,y), pw=0, \
NameError: global name 'FGC' is not defined

If I build the code from scratch but change the variable "FGC" to "settings.FGC", it works perfectly fine, so I think this is a simple fix.

Thanks!

**Comment by esdalmaijer** [comment]
Thanks for pointing this out! It's fixed with https://github.com/esdalmaijer/PyGaze/commit/c03473c6d093cc75d9b33b32ac30d9e3105f566d
