### ISSUE TITLE
windll not defined

### ISSUE THREAD

**Issue by yasethiya** [esdalmaijer/PyGaze#95]
While executing  `python simple_tracker_experiment.py `
`Traceback (most recent call last):
  File "simple_tracker_experiment.py", line 20, in <module>
    tracker = eyetracker.EyeTracker(disp)
  File "/usr/local/lib/python2.7/dist-packages/pygaze/eyetracker.py", line 73, in __init__
    from pygaze._eyetracker.libsmi import SMItracker
  File "/usr/local/lib/python2.7/dist-packages/pygaze/_eyetracker/libsmi.py", line 42, in <module>
    from iViewXAPI import  *
  File "/usr/local/lib/python2.7/dist-packages/pygaze/_eyetracker/iViewXAPI.py", line 74, in <module>
    iViewXAPI = windll.LoadLibrary("iViewXAPI.dll")
NameError: name 'windll' is not defined
`

**Comment by esdalmaijer** [comment]
`windll` should be imported from `ctypes`, but this module is only available on Windows. Were you running this on Linux or OS X? Were you intending to use SMI on them?

**Comment by bloddie** [comment]
hi, i currently have the same issue. I'm trying to run the file off a rasberry Pi (linux).

**Comment by chukidadiz** [comment]
I encounter this error aswell does it mean it only work ins windows?

**Comment by esdalmaijer** [comment]
As said before, the error relates to the SMI implementation, which is Windows-only.

If you're trying to use an SMI tracker on a different operating system, please refer to SMI, as I don't think they support anything else.

If you're not trying to use an SMI tracker, then you should be setting a different `TRACKERTYPE` in your `constants.py` file.
